foursquare_nyc:
  learning_rate: 1e-4
  reg_weight: 100
foursquare_tky:
  learning_rate: 1e-4
  reg_weight: 100
ijcai_15_repeat_buyers_80:
  learning_rate:
  reg_weight:
insurance:
  learning_rate:
  reg_weight:
lastfm-1k:
  learning_rate:
  reg_weight:
lastfm-1m:
  learning_rate: 2e-4
  reg_weight: 100
ml-1m:
  learning_rate: 2e-4
  reg_weight: 2000
rent_the_runway:
  learning_rate: 1e-4
  reg_weight: 500
tafeng:
  learning_rate:
  reg_weight:
