foursquare_nyc:
  learning_rate: 2e-4
foursquare_tky:
  learning_rate: 2e-4
ijcai_15_repeat_buyers_80:
insurance:
  learning_rate: 2e-4
lastfm-1k:
  learning_rate: 2e-4
lastfm-1m:
  learning_rate: 2e-4
ml-1m:
  learning_rate: 2e-4
rent_the_runway:
  learning_rate: 2e-4
tafeng:
  learning_rate: 2e-4
