foursquare_nyc:
  dropout_prob: 0.1
  mlp_hidden_size: [600,600]
  learning_rate: 2e-4
  latent_dimension: 200
foursquare_tky:
  dropout_prob: 0.5
  mlp_hidden_size: [600]
  learning_rate: 2e-4
  latent_dimension: 200
ijcai_15_repeat_buyers_80:
  dropout_prob:
  mlp_hidden_size:
  latent_dimension:
insurance:
  dropout_prob:
  mlp_hidden_size:
  latent_dimension:
lastfm-1k:
  dropout_prob:
  mlp_hidden_size:
  latent_dimension:
lastfm-1m:
  dropout_prob: 0.1
  mlp_hidden_size: [600]
  learning_rate: 2e-4
  latent_dimension: 200
ml-1m:
  dropout_prob: 0.3
  mlp_hidden_size: [600]
  learning_rate: 2e-4
  latent_dimension: 200
rent_the_runway:
  dropout_prob: 0.5
  mlp_hidden_size: [600,600]
  learning_rate: 2e-4
  latent_dimension: 200
tafeng:
  dropout_prob:
  mlp_hidden_size:
  latent_dimension:
