foursquare_nyc:
  learning_rate: 2e-4
  message_dropout: 0.0
  node_dropout: 0.0
foursquare_tky:
  learning_rate: 2e-4
  message_dropout: 0.0
  node_dropout: 0.0
ijcai_15_repeat_buyers_80:
insurance:
  learning_rate: 1e-4
  message_dropout: 0.1
  node_dropout: 0.1
lastfm-1k:
  learning_rate: 2e-4
  message_dropout: 0.0
  node_dropout: 0.1
lastfm-1m:
  learning_rate: 2e-4
  message_dropout: 0.0
  node_dropout: 0.0
ml-1m:
  learning_rate: 2e-4
  message_dropout: 0.0
  node_dropout: 0.0
rent_the_runway:
  learning_rate: 2e-4
  message_dropout: 0.0
  node_dropout: 0.1
tafeng:
  learning_rate: 2e-4
  message_dropout: 0.1
  node_dropout: 0.1
