foursquare_nyc:
  eps: 0.2
  lambda: 0.05
  learning_rate: 2e-4
  temperature: 0.1
foursquare_tky:
  eps: 0.2
  lambda: 0.05
  learning_rate: 2e-4
  temperature: 0.1
ijcai_15_repeat_buyers_80:
insurance:
  eps: 0.1
  lambda: 0.1
  learning_rate: 2e-4
  temperature: 0.05
lastfm-1k:
  eps: 0.2
  lambda: 0.05
  learning_rate: 2e-4
  temperature: 0.1
lastfm-1m:
  eps: 0.2
  lambda: 0.1
  learning_rate: 1e-4
  temperature: 0.1
ml-1m:
  eps: 0.2
  lambda: 0.05
  learning_rate: 2e-4
  temperature: 0.1
rent_the_runway:
  eps: 0.1
  lambda: 0.1
  learning_rate: 2e-4
  temperature: 0.1
tafeng:
  eps: 0.2
  lambda: 0.05
  learning_rate: 2e-4
  temperature: 0.1
