enable_sparse: True
worker: 0
epochs: 300
# 'USER_ID_FIELD': 'user_id'
# 'ITEM_ID_FIELD': 'item_id'
TIME_FIELD: 'timestamp'
train_batch_size: 4096
eval_batch_size: 2048
train_neg_sample_args:          # (dict) Negative sampling configuration for model training.
  distribution: uniform         # (str) The distribution of negative items.
  sample_num: 10                # (int) The sampled num of negative items.
  alpha: 1.0                    # (float) The power of sampling probability for popularity distribution.
  dynamic: False                # (bool) Whether to use dynamic negative sampling.
  candidate_num: 0
eval_step: 2
metrics: ['Recall', 'NDCG', 'MRR', 'Hit', 'Precision', 'DeltaNDCG']
topk: 10
valid_metric: NDCG@10
metric_decimal_place: 4
learning_rate: 0.001
reg_weight: 1e-05  #[1e-05,1e-04,1e-03,1e-02]
eval_args:
    split: {'LRS': None}
    order: RO  # not relevant
    group_by: '-'
    mode: 'full'

data_path: '../../../recsysdatasets'
require_pow: False              # (bool) Whether or not to perform power operation in EmbLoss.
enable_amp: True                # (bool) Whether or not to use mixed precision training.
enable_scaler: False            # (bool) Whether or not to use GradScaler in mixed precision training.
transform: ~                    # (str) The transform operation for batch data process.

# checkpoint_dir: 'dataset/processed'
# save_dataset: True
save_dataloaders: True
seed: 43
load_col: {'inter': ['user_id', 'item_id', 'timestamp']}

item_discriminative_attribute: visibility
short_head_item_discriminative_ratio: 0.2
item_discriminative_map: ['[PAD]', SH, LT]  # SH: Short Head, LT: Long Tail

fair_metric_statistic: mannwhitneyu
recbole_hyper_algo: bayes
