TIME_FIELD: 'time_stamp'
train_batch_size: 4096
eval_batch_size: 500000
# sensitive attributes to be used in the fairness losses and for following analysis
sensitive_attribute: gender

load_col:
    inter: [user_id, item_id, time_stamp]
    user: [user_id, gender, age]
unused_col: {'inter': ['time_stamp']}

# NCL
num_clusters: 500
