# USER_ID_FIELD: 'user_id'
ITEM_ID_FIELD: 'artist_name'
# TIME_FIELD: 'timestamp'
train_batch_size: 4096
eval_batch_size: 2048
# sensitive attributes to be used in the fairness losses and for following analysis
sensitive_attribute: gender

load_col:
    inter: [user_id, artist_name, timestamp]
    user: [user_id, gender, age]
